### ISSUE TITLE
How to get HTML content from the editor

### ISSUE THREAD

**Issue by alexbagirov** [wbb/wysibb#117]
For example I have embedded wysibb on the page and I need to write something, save it in MySQL and show as HTML on another page. How it is possible to do so?

Thanks.

**Comment by wbb** [comment]
$("#editor").htmlcode(); //Get HTML content

**Comment by alexbagirov** [comment]
Ok, but how can I bring it to PHP so it will push text to database?

**Comment by TxYxLxExR** [comment]
LOL! It's quite simple actually... I am not entirely sure why but the textarea doesn't retain the proper value as it should. So due to lack of a functioning plugin, support and no other better options i found my own solution. Minimal coding experience needed, not ;)
This might not be your exact answer because I am using bbcode instead so please keep that in mind. But everything here I wrote myself. Start with your basic field as you would.. However, make a copy of it, with the same name and empty contents, a UNIQUE ID and make sure it is hidden with css.

On page load, you are going to want to reset the name attribute for the first field you created (your main field - text editor). I did it this way because it didn't require me to further modify my code due to the fact we will be copying the editors contents. So it just allowed me to not modify where i fetch the $_POST data

So instead of something like this:
$('#texteditor_id').wysibb()
you want something like this
$('#texteditor_id').attr('name', 'test_bbcode').wysibb()


and then you are going to want a code like the following (I left some lines commented out in case people wanted to test it prior to sending the data to the server)
$('#if_of_hidden_textarea').on('submit', function(){
		$('#texteditor_id').sync();
		$('#id_of_hidden_textarea').html($('#texteditor_id').val());
//alert($('#texteditor_id').val());
//return false;
	});

This will then have the proper post data you need! I did have to fix an error in the main plugin file... So keep that in mind as well.. Hopefully this will help someone.
